# Generated by Django 3.1.5 on 2021-04-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=150)),
                ('LastName', models.CharField(max_length=150)),
                ('Email', models.CharField(max_length=150)),
                ('DateOfBirth', models.CharField(max_length=150)),
                ('MobileNumber', models.CharField(max_length=10)),
                ('DoctorLicense', models.FileField(upload_to='DoctorDocuments/')),
                ('YearsOfExperience', models.IntegerField(max_length=2)),
                ('Education', models.CharField(max_length=250)),
                ('Masters', models.CharField(max_length=250)),
                ('HospitalName', models.CharField(max_length=50)),
                ('Department', models.IntegerField(choices=[(1, 'General Health'), (2, 'Cardiology'), (3, 'Dental'), (4, 'Medical Research'), (5, 'Emergency'), (6, 'Gynecologist')], default=1)),
                ('Description', models.CharField(max_length=150)),
                ('Achievements1', models.CharField(max_length=50)),
                ('Achievements2', models.CharField(max_length=50)),
                ('Achievements3', models.CharField(max_length=50)),
                ('Achievements4', models.CharField(max_length=50)),
            ],
        ),
    ]
