# Generated by Django 3.1.5 on 2021-04-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_doctors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='YearsOfExperience',
            field=models.IntegerField(),
        ),
    ]
