# Generated by Django 3.1.5 on 2021-04-08 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='ratings',
            new_name='rating',
        ),
        migrations.AddField(
            model_name='review',
            name='review',
            field=models.TextField(blank=True),
        ),
    ]
