# Generated by Django 3.1.5 on 2021-04-08 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_username'),
        ('accounts', '0002_auto_20210402_2026'),
        ('reviews', '0002_auto_20210408_0946'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='DocReview',
        ),
    ]
