# Generated by Django 3.1.5 on 2021-04-08 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20210408_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='docreview',
            name='review_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
