# Generated by Django 3.1.5 on 2021-04-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_hosreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docreview',
            name='rating',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hosreview',
            name='rating',
            field=models.TextField(blank=True),
        ),
    ]
