# Generated by Django 3.1.5 on 2021-04-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20210410_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docreview',
            old_name='rating',
            new_name='non_rating',
        ),
        migrations.RenameField(
            model_name='hosreview',
            old_name='rating',
            new_name='non_rating',
        ),
        migrations.AddField(
            model_name='docreview',
            name='star_rating',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hosreview',
            name='star_rating',
            field=models.TextField(blank=True),
        ),
    ]
