# Generated by Django 3.1.5 on 2021-04-08 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20210402_2026'),
        ('doctors', '0002_doctor_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourEmail', models.EmailField(max_length=254)),
                ('dateOfAppointment', models.DateField()),
                ('yourPhonenumber', models.CharField(blank=True, max_length=15)),
                ('AdditionalMessage', models.TextField(max_length=500)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='doctors.doctor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.user')),
            ],
        ),
    ]
