# Generated by Django 3.1.5 on 2021-04-09 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='yourEmail',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='yourPhonenumber',
        ),
    ]
