# Generated by Django 3.1.5 on 2021-04-26 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_hospital_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='Ratings_count',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
