# Generated by Django 3.1.5 on 2021-04-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_hospital_ratings_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='Ratings_count',
            field=models.IntegerField(default=0),
        ),
    ]
