# Generated by Django 3.1.5 on 2021-05-04 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0007_auto_20210429_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='Achievements1',
            field=models.CharField(default='No Hospital information added recently', max_length=50),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='Achievements2',
            field=models.CharField(default='No Hospital information added recently', max_length=50),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='Achievements3',
            field=models.CharField(default='No Hospital information recently', max_length=50),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='Achievements4',
            field=models.CharField(default='No achievements added recently', max_length=50),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='Achievements5',
            field=models.CharField(default='No achievements added recently', max_length=50),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='Achievements6',
            field=models.CharField(default='No achievements added recently', max_length=50),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='CheifMedicalOfficerDescription',
            field=models.CharField(default='Dear, be strong because your life will be better now. Time does not remain same. You will get well soon!', max_length=250),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='HospitalDescription',
            field=models.TextField(default='Dear, be strong because your life will be better now. Time does not remain same. You will get well soon!', max_length=250),
        ),
    ]
