# Generated by Django 3.1.5 on 2021-05-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0010_auto_20210504_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='ChiefMedicalOfficerPhoto',
            field=models.FileField(default='DefaultPhotos/doctt.png', upload_to='ChiefDoctorPhotos/'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='HospitalPhoto',
            field=models.FileField(default='DefaultPhotos/hospitalPhotos.jpg', upload_to='HospitalPhotos/'),
        ),
    ]
