# Generated by Django 3.1.5 on 2021-04-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=150)),
                ('LastName', models.CharField(max_length=150)),
                ('Email', models.CharField(max_length=150)),
                ('DateOfBirth', models.CharField(max_length=150)),
                ('ProfilePhoto', models.FileField(blank=True, upload_to='DoctorPhotos/')),
                ('MobileNumber', models.CharField(max_length=10)),
                ('DoctorLicense', models.FileField(upload_to='DoctorDocuments/')),
                ('YearsOfExperience', models.IntegerField(blank=True)),
                ('Education', models.CharField(blank=True, max_length=250)),
                ('Masters', models.CharField(blank=True, max_length=250)),
                ('HospitalName', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=100)),
                ('State', models.IntegerField(choices=[(1, 'Andhra Pradesh'), (2, 'Arunachal Pradesh'), (3, 'Assam'), (4, 'Bihar'), (5, 'Chhattisgarh'), (6, 'Goa'), (7, 'Gujarat'), (8, 'Harayana'), (9, 'Himachal Pradesh'), (10, 'Jharkhand'), (11, 'Karnataka'), (12, 'Kerala'), (13, 'Madhya Pradesh'), (14, 'Maharashtra'), (15, 'Manipur'), (16, 'Meghalaya'), (17, 'Mizoram'), (18, 'Nagaland'), (19, 'Odisha'), (20, 'Punjab'), (21, 'Rajasthan'), (22, 'Sikkim'), (23, 'Tamil Nadu'), (24, 'Telangana'), (25, 'Tripura'), (26, 'Uttarakhand'), (27, 'Uttar Pradesh'), (28, 'West Bengal')], default=1)),
                ('Pincode', models.CharField(max_length=20)),
                ('Department', models.IntegerField(choices=[(1, 'General Health'), (2, 'Cardiology'), (3, 'Dental'), (4, 'Medical Research'), (5, 'Emergency'), (6, 'Gynecologist')], default=1)),
                ('Description', models.CharField(blank=True, max_length=150)),
                ('Achievements1', models.CharField(blank=True, max_length=50)),
                ('Achievements2', models.CharField(blank=True, max_length=50)),
                ('Achievements3', models.CharField(blank=True, max_length=50)),
                ('Achievements4', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
