# Generated by Django 3.1.5 on 2021-04-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Username',
            field=models.CharField(default='', max_length=150),
        ),
    ]
