# Generated by Django 3.1.5 on 2021-04-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_auto_20210411_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
