# Generated by Django 3.1.5 on 2021-04-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_doctor_ratings_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Ratings_count',
            field=models.IntegerField(default=0),
        ),
    ]
