# Generated by Django 3.1.5 on 2021-04-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_auto_20210426_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Ratings_stars',
            field=models.CharField(default='', max_length=5),
        ),
    ]
