# Generated by Django 3.1.5 on 2021-04-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_auto_20210429_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='HospitalRegisterationNumber',
            field=models.CharField(default='', max_length=100),
        ),
    ]
