# Generated by Django 3.1.5 on 2021-05-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0011_auto_20210503_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='ProfilePhoto',
            field=models.FileField(default='DoctorPhotos/boy_avatar.jpg', upload_to='DoctorPhotos/'),
        ),
    ]
