# Generated by Django 3.1.7 on 2021-05-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0012_auto_20210503_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Achievements1',
            field=models.CharField(default='No achievements added recently', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Achievements2',
            field=models.CharField(default='No achievements added recently', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Achievements3',
            field=models.CharField(default='No achievements added recently', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Achievements4',
            field=models.CharField(default='No achievements added recently', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Department',
            field=models.IntegerField(choices=[(1, 'General Health'), (2, 'Cardiology'), (3, 'Dental'), (4, 'Medical Research'), (5, 'Emergency'), (6, 'Gynecologist'), (7, 'All')], default=1),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Description',
            field=models.CharField(default='Dear, be strong because your life will be better now. Time does not remain same. You will get well soon!', max_length=150),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='HospitalRegisterationNumber',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='State',
            field=models.IntegerField(choices=[(1, 'Andhra Pradesh'), (2, 'Arunachal Pradesh'), (3, 'Assam'), (4, 'Bihar'), (5, 'Chhattisgarh'), (6, 'Goa'), (7, 'Gujarat'), (8, 'Haryana'), (9, 'Himachal Pradesh'), (10, 'Jharkhand'), (11, 'Karnataka'), (12, 'Kerala'), (13, 'Madhya Pradesh'), (14, 'Maharashtra'), (15, 'Manipur'), (16, 'Meghalaya'), (17, 'Mizoram'), (18, 'Nagaland'), (19, 'Odisha'), (20, 'Punjab'), (21, 'Rajasthan'), (22, 'Sikkim'), (23, 'Tamil Nadu'), (24, 'Telangana'), (25, 'Tripura'), (26, 'Uttarakhand'), (27, 'Uttar Pradesh'), (28, 'West Bengal'), (29, 'All')], default=1),
        ),
    ]
