# Generated by Django 3.1.5 on 2021-05-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0012_auto_20210503_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Achievements1',
            field=models.CharField(default='No achievements added recently', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Achievements2',
            field=models.CharField(default='No achievements added recently', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Achievements3',
            field=models.CharField(default='No achievements added recently', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Achievements4',
            field=models.CharField(default='No achievements added recently', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Description',
            field=models.CharField(default='Dear, be strong because your life will be better now. Time does not remain same. You will get well soon!', max_length=150),
        ),
    ]
