# Generated by Django 3.1.7 on 2021-05-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0013_auto_20210503_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Department',
            field=models.IntegerField(choices=[(1, 'General Health'), (2, 'Cardiology'), (3, 'Dental'), (4, 'Medical Research'), (5, 'Emergency'), (6, 'Gynecologist'), (7, 'All')], default=1),
        ),
    ]
