# Generated by Django 3.1.5 on 2021-05-04 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0013_auto_20210503_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='HospitalRegisterationNumber',
            field=models.CharField(max_length=100),
        ),
    ]
