# Generated by Django 3.1.5 on 2021-05-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0013_auto_20210504_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Education',
            field=models.CharField(default='Not available', max_length=250),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Masters',
            field=models.CharField(default='Not available', max_length=250),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='MobileNumber',
            field=models.CharField(default='Not available', max_length=10),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Username',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='YearsOfExperience',
            field=models.IntegerField(default=0),
        ),
    ]
